
version: '3.1'

services:

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  api:
    build: .
    depends_on:
      - db
    environment:
      NODE_ENV: development
      PORT: 3000
    ports:
      - "3000:3000"
      - "9229:9229"
    command: npm run debug
    volumes:
      - .:/app/

  db:
    image: postgres:14
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: seq
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: database_development
    volumes:
      - "pg_data:/var/lib/postgresql/data"

volumes:
  pg_data: